----------------------------------------------------------------------
-- TEARDOWN: Drop all objects created during testing
-- (keeps RAW_FILES_UPLOAD stage intact)
----------------------------------------------------------------------

USE ROLE DNA_INF_DATA_SCIENCE;

-- Cortex Agent
DROP AGENT IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.DOCUMENT_AGENT;

-- Cortex Search Service
DROP CORTEX SEARCH SERVICE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.DOCUMENT_SEARCH_SERVICE;

-- Tables
DROP TABLE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.CHUNKED_DOCUMENTS;
DROP TABLE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.CLEANED_DOCUMENTS;
DROP TABLE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.ENRICHED_DOCUMENTS;
DROP TABLE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.IMAGE_DESCRIPTIONS;
DROP TABLE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.PARSED_DOCUMENTS;

-- Stages (keeping RAW_FILES_UPLOAD)
DROP STAGE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.EXTRACTED_IMAGES;

-- Procedures
DROP PROCEDURE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.CONVERT_UNSUPPORTED_FILES();
DROP PROCEDURE IF EXISTS DEV_SANDBOX.ABRETHO__RAW_FILES.SAVE_IMAGES_TO_STAGE();
